/** Minimal ABI for the current CertTraceRegistry contract. */
export const CERTTRACE_REGISTRY_ABI = [
  "error AdminOnly(address account)",
  "error CredentialAlreadyExists(bytes32 credentialId)",
  "error CredentialAlreadyRevoked(bytes32 credentialId)",
  "error CredentialIssuerOnly(address account, address credentialIssuer)",
  "error InvalidCommitment()",
  "error InvalidCredentialId()",
  "error InvalidIssuerAddress()",
  "error IssuerAlreadyAuthorized(address issuer)",
  "error IssuerNotAuthorized(address issuer)",
  "error UnknownCredential(bytes32 credentialId)",
  "event CredentialIssued(bytes32 indexed credentialId, bytes32 indexed commitment, address indexed issuer, uint64 issuedAt)",
  "event CredentialRevoked(bytes32 indexed credentialId, address indexed issuer, uint64 revokedAt)",
  "event IssuerAuthorized(address indexed issuer)",
  "event IssuerRemoved(address indexed issuer)",
  "function admin() view returns (address)",
  "function authorizeIssuer(address issuer)",
  "function authorizedIssuers(address account) view returns (bool)",
  "function getCredential(bytes32 credentialId) view returns ((bytes32 commitment, address issuer, uint64 issuedAt, bool revoked, uint64 revokedAt, bool exists))",
  "function isAuthorizedIssuer(address account) view returns (bool)",
  "function isCredentialActive(bytes32 credentialId) view returns (bool)",
  "function issueCredential(bytes32 credentialId, bytes32 commitment)",
  "function removeIssuer(address issuer)",
  "function revokeCredential(bytes32 credentialId)",
] as const;
